apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "smartnote.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - {{ .Values.web.host }}
      - www.{{ .Values.web.host }}
      secretName: {{ include "smartnote.fullname" . }}
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "smartnote.fullname" . }}
            servicePort: phoenix
  - host: www.{{ .Values.web.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "smartnote.fullname" . }}
            servicePort: phoenix
